name: upload static website to S3 on push
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to S3
        #-- GitHub上に登録した変数を持ってくる --#
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #-- 仮想マシン上でコマンドを実行 --#
        run:
          aws s3 sync --delete --region ap-northeast-1 ./ s3://tsukuda-office.com
        
